In [51]:
import pandas as pd

In [52]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Untitled.ipynb']

In [53]:
df = pd.read_csv(r'C:\Users\R.K COM\Downloads\customer_shopping_behavior.csv')

In [54]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [55]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [56]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [57]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [58]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [59]:
df['Review Rating']

0       3.1
1       3.1
2       3.1
3       3.5
4       2.7
       ...
3895    4.2
3896    4.5
3897    2.9
3898    3.8
3899    3.1
Name: Review Rating, Length: 3900, dtype: float64

In [60]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [61]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [62]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [63]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [64]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [65]:
# CREATE A AGE COLUMN IN AGE GROUP

In [66]:
labels= ['young_adult , middle_age, senior, adult']

In [67]:
labels = ['Young_age', 'Adult', 'Middle_Age', 'Senior']

df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [68]:
print(df.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group'],
      dtype='str')

In [69]:
df[['age','age_group']].head(20)

    age   age_group
0    55  Middle_Age
1    19   Young_age
2    50  Middle_Age
3    21   Young_age
4    45  Middle_Age
5    46  Middle_Age
6    63      Senior
7    27   Young_age
8    26   Young_age
9    57  Middle_Age
10   53  Middle_Age
11   30   Young_age
12   61      Senior
13   65      Senior
14   64      Senior
15   64      Senior
16   25   Young_age
17   53  Middle_Age
18   52  Middle_Age
19   66      Senior

In [70]:
# CREATE A COLUMN ADD PURCHASE FREQUENCY DAYS

In [71]:
df.frequency_of_purchases.head(20)

0     Fortnightly
1     Fortnightly
2          Weekly
3          Weekly
4        Annually
5          Weekly
6       Quarterly
7          Weekly
8        Annually
9       Quarterly
10      Bi-Weekly
11    Fortnightly
12    Fortnightly
13         Weekly
14         Weekly
15        Monthly
16      Bi-Weekly
17      Quarterly
18         Weekly
19      Bi-Weekly
Name: frequency_of_purchases, dtype: str

In [72]:
frequncy_mapping = {'Fortnightly':14,
                 'Weekly':7,
                 'Bi-Weekly':14,
                 'Quarterly':90,
                 'Annually':365,
                 'Monthly':30,
                'Every 3 Months':90}

df['purchase_frequncy_days'] = df['frequency_of_purchases'].map(frequncy_mapping)

In [73]:
df[['purchase_frequncy_days','frequency_of_purchases']].head(20)

    purchase_frequncy_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly
10                      14              Bi-Weekly
11                      14            Fortnightly
12                      14            Fortnightly
13                       7                 Weekly
14                       7                 Weekly
15                      30                Monthly
16                      14              Bi-Weekly
17                      90              Quarterly
18                       7                 Weekly
19                      14              Bi-Weekly

In [74]:
# AB HUM CHECK KARENGE KI DO COLUMN ME SAME VALUE HAI YA NHI JAISE KI 'discount_applied'AND 'promo_code_used' IN DDONO COLUMN

In [75]:
df[['discount_applied', 'promo_code_used']].head(20)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes
11              Yes             Yes
12              Yes             Yes
13              Yes             Yes
14              Yes             Yes
15              Yes             Yes
16              Yes             Yes
17              Yes             Yes
18              Yes             Yes
19              Yes             Yes

In [76]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [77]:
# ek coloumn ko remove kr denge

In [78]:
df = df.drop('promo_code_used',axis=1)

In [80]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequncy_days'],
      dtype='str')